site_name: "Botshare Book"
site_url: "https://merilynn-64.github.io/Botshare_document/"
repo_url: "https://github.com/openAMRobot"
repo_name: "GitHub"

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.section
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: dark blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: assets/logo.jpg
  favicon: assets/favicon.png 

extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:info@botshare.ai
    - icon: fontawesome/brands/github
      link: https://github.com/openAMRobot
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/botshare

nav:
  - Home:
      - Welcome: index.md
      - Level-1: level-1.md
      - Level-2: level-2.md
      - Level-3: level-3.md
      - About Us: about-us.md
      
  - L1-Incubation:
      - Overview: L1-Incubation/index.md
      - Homepage: level-1.md
      - Lessons:
        - Lesson 1: L1-Incubation/Lessons/lesson-1.md
        - Lesson 2: L1-Incubation/Lessons/lesson-2.md
        - Lesson 3: L1-Incubation/Lessons/lesson-3.md
      - About Us: about-us.md 
  - L2-Aceleration:
      - Overview: L2-Acceleration/index.md
      - Lessons:
        - Lesson 1: L2-Acceleration/Lessons/lesson-1.md
        - Lesson 2: L2-Acceleration/Lessons/lesson-2.md
        - Lesson 3: L2-Acceleration/Lessons/lesson-3.md
        
  - L3-Mastery:
      - Overview: L3-Mastery/index.md
      - Lessons:
        - Lesson 1: L3-Mastery/Lessons/lesson-1.md
        - Lesson 2: L3-Mastery/Lessons/lesson-2.md
        - Lesson 3: L3-Mastery/Lessons/lesson-3.md     
        
  - Company:
      - About us: about-us.md
      - Contributing: contributing.md
      - FAQ: faq.md
  

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
