site_name: "Botshare Book"
site_url: "https://merilynn-64.github.io/Botshare_document/"
repo_url: "https://github.com/openAMRobot"
baseurl: "/Botshare_document"
repo_name: "GitHub"

theme:
  name: "material"
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.section
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: dark blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  #logo: assets/botshare_logo.png
  favicon: assets/favicon.png 
  
extra:
  generator: false
  
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:info@botshare.ai
    - icon: fontawesome/brands/github
      link: https://github.com/openAMRobot
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/botshare

nav:
  - Home:
      - Welcome: index.md
      - Getting Started: getting_started.md
      - User Guide: user-guide.md
      - Donation: donation.md
      - About Us: about-us.md
      
  - Beginner:
      - Overview: Beginner/index.md
      - Learn by Subject: 
        - Analog Electronics: Beginner/learn-by-subject/analog-electronics.md
        - Biosignal Processing: Beginner/learn-by-subject/biosignal-processing.md
        - Digital Electronics: Beginner/learn-by-subject/digital-electronics.md
        - Maths 101: Beginner/learn-by-subject/maths-101.md
        - Object-Oriented Design: Beginner/learn-by-subject/object-oriented-design.md
        - Physics: Beginner/learn-by-subject/physics.md
        - Programming Basics: Beginner/learn-by-subject/programming-basics.md
        - Version Control: Beginner/learn-by-subject/version-control.md
      - Learn by Industry:
        - Smart House: Beginner/learn-by-industry/smart-house.md
        - Smart Green House: Beginner/learn-by-industry/smart-green-house.md
        - Smart Factory:  Beginner/learn-by-industry/smart-factory.md
        - Smart Settlement:  Beginner/learn-by-industry/smart-settlement-on-mars.md
      - Lessons:
        - Lesson 1: Beginner/Lessons/lesson_1.md
        - Lesson 2: Beginner/Lessons/lesson_2.md
        - Lesson 3: Beginner/Lessons/lesson_3.md
        - Lesson 4: Beginner/Lessons/lesson_4.md
        - Lesson 5: Beginner/Lessons/lesson_5.md
        - Lesson 6: Beginner/Lessons/lesson_6.md
        - Lesson 7: Beginner/Lessons/lesson_7.md
        - Lesson 8: Beginner/Lessons/lesson_8.md
        - Lesson 9: Beginner/Lessons/lesson_9.md
        - Lesson 10: Beginner/Lessons/lesson_10.md
        - Lesson 11: Beginner/Lessons/lesson_11.md
        - Lesson 12: Beginner/Lessons/lesson_12.md
        - Lesson 13: Beginner/Lessons/lesson_13.md
        - Lesson 14: Beginner/Lessons/lesson_14.md
        - Lesson 15: Beginner/Lessons/lesson_15.md
        - Lesson 16: Beginner/Lessons/lesson_16.md
        - Lesson 17: Beginner/Lessons/lesson_17.md
        - Lesson 18: Beginner/Lessons/lesson_18.md
        - Lesson 19: Beginner/Lessons/lesson_19.md
        - Lesson 20: Beginner/Lessons/lesson_20.md
        - Lesson 21: Beginner/Lessons/lesson_21.md
        - Lesson 22: Beginner/Lessons/lesson_22.md
        - Lesson 23: Beginner/Lessons/lesson_23.md
        - Lesson 24: Beginner/Lessons/lesson_24.md
        - Lesson 25: Beginner/Lessons/lesson_25.md
        - Lesson 26: Beginner/Lessons/lesson_26.md
        - Lesson 27: Beginner/Lessons/lesson_27.md
        - Lesson 28: Beginner/Lessons/lesson_28.md
        - Lesson 29: Beginner/Lessons/lesson_29.md
        - Lesson 30: Beginner/Lessons/lesson_30.md
        - Lesson 31: Beginner/Lessons/lesson_31.md
        - Lesson 32: Beginner/Lessons/lesson_32.md
        - Lesson 33: Beginner/Lessons/lesson_33.md
        - Lesson 34: Beginner/Lessons/lesson_34.md
        - Lesson 35: Beginner/Lessons/lesson_35.md
        - Lesson 36: Beginner/Lessons/lesson_36.md
        - Lesson 37: Beginner/Lessons/lesson_37.md
        - Lesson 38: Beginner/Lessons/lesson_38.md
        - Lesson 39: Beginner/Lessons/lesson_39.md
        - Lesson 40: Beginner/Lessons/lesson_40.md
        - Lesson 41: Beginner/Lessons/lesson_41.md
        - Lesson 42: Beginner/Lessons/lesson_42.md
        - Lesson 43: Beginner/Lessons/lesson_43.md
        - Lesson 44: Beginner/Lessons/lesson_44.md
        - Lesson 45: Beginner/Lessons/lesson_45.md
        - Lesson 46: Beginner/Lessons/lesson_46.md
        - Lesson 47: Beginner/Lessons/lesson_47.md
        - Lesson 48: Beginner/Lessons/lesson_48.md
        - Lesson 49: Beginner/Lessons/lesson_49.md
        - Lesson 50: Beginner/Lessons/lesson_50.md
        - Lesson 51: Beginner/Lessons/lesson_51.md
        - Lesson 52: Beginner/Lessons/lesson_52.md
        - Lesson 53: Beginner/Lessons/lesson_53.md
        - Lesson 54: Beginner/Lessons/lesson_54.md
        - Lesson 55: Beginner/Lessons/lesson_55.md
        - Lesson 56: Beginner/Lessons/lesson_56.md
        - Lesson 57: Beginner/Lessons/lesson_57.md
        - Lesson 58: Beginner/Lessons/lesson_58.md
        - Lesson 59: Beginner/Lessons/lesson_59.md
        - Lesson 60: Beginner/Lessons/lesson_60.md
        - Lesson 61: Beginner/Lessons/lesson_61.md
        - Lesson 62: Beginner/Lessons/lesson_62.md
        - Lesson 63: Beginner/Lessons/lesson_63.md
        - Lesson 64: Beginner/Lessons/lesson_64.md
        - Lesson 65: Beginner/Lessons/lesson_65.md
        - Lesson 66: Beginner/Lessons/lesson_66.md
        - Lesson 67: Beginner/Lessons/lesson_67.md
        - Lesson 68: Beginner/Lessons/lesson_68.md
        - Lesson 69: Beginner/Lessons/lesson_69.md
        - Lesson 70: Beginner/Lessons/lesson_70.md
        - Lesson 71: Beginner/Lessons/lesson_71.md
        - Lesson 72: Beginner/Lessons/lesson_72.md
        - Lesson 73: Beginner/Lessons/lesson_73.md
        - Lesson 74: Beginner/Lessons/lesson_74.md
        - Lesson 75: Beginner/Lessons/lesson_75.md
        - Lesson 76: Beginner/Lessons/lesson_76.md
        - Lesson 77: Beginner/Lessons/lesson_77.md
        - Lesson 78: Beginner/Lessons/lesson_78.md
        - Lesson 79: Beginner/Lessons/lesson_79.md
        - Lesson 80: Beginner/Lessons/lesson_80.md
        - Lesson 81: Beginner/Lessons/lesson_81.md
        - Lesson 82: Beginner/Lessons/lesson_82.md
        - Lesson 83: Beginner/Lessons/lesson_83.md
        - Lesson 84: Beginner/Lessons/lesson_84.md
        - Lesson 85: Beginner/Lessons/lesson_85.md
        - Lesson 86: Beginner/Lessons/lesson_86.md
        - Lesson 87: Beginner/Lessons/lesson_87.md
        - Lesson 88: Beginner/Lessons/lesson_88.md
        - Lesson 89: Beginner/Lessons/lesson_89.md
        - Lesson 90: Beginner/Lessons/lesson_90.md
        - Lesson 91: Beginner/Lessons/lesson_91.md
        - Lesson 92: Beginner/Lessons/lesson_92.md
        - Lesson 93: Beginner/Lessons/lesson_93.md
        - Lesson 94: Beginner/Lessons/lesson_94.md
        - Lesson 95: Beginner/Lessons/lesson_95.md
        - Lesson 96: Beginner/Lessons/lesson_96.md
        - Lesson 97: Beginner/Lessons/lesson_97.md
        - Lesson 98: Beginner/Lessons/lesson_98.md
        - Lesson 99: Beginner/Lessons/lesson_99.md
        - Lesson 100: Beginner/Lessons/lesson_100.md

      
  - Intermediate:
      - Overview: Intermediate/index.md
      - Learn by Subject: 
        - Algorithms: Intermediate/learn-by-subject/algorithms.md
        - Communication Protocols: Intermediate/learn-by-subject/communication-protocols.md
        - Computer Vision: Intermediate/learn-by-subject/computer-vision.md
        - Control System: Intermediate/learn-by-subject/control-system.md
        - Embedded System: Intermediate/learn-by-subject/embedded-system.md
        - Mechatronics: Intermediate/learn-by-subject/mechatronics.md
        - Power and Battery: Intermediate/learn-by-subject/power-and-battery.md
        - Prototyping and Fabrication: Intermediate/learn-by-subject/prototyping-and-fabrication.md
        - Robotics Middleware: Intermediate/learn-by-subject/robotics-middleware.md
        - Sensors and Actuators: Intermediate/learn-by-subject/sensors-and-actuators.md
      - Learn by Industry:
        - Human Machine Interface: Intermediate/learn-by-industry/human-machine-interface.md
        - Mechatronics:  Intermediate/learn-by-industry/mechatronics.md
        - Ros 2:  Intermediate/learn-by-industry/ros-2.md
        - Automation Warehouse:  Intermediate/learn-by-industry/automation-warehouse.md
      - Lessons:
        - Lesson 1: Intermediate/Lessons/lesson_1.md
        - Lesson 2: Intermediate/Lessons/lesson_2.md
        - Lesson 3: Intermediate/Lessons/lesson_3.md
        - Lesson 4: Intermediate/Lessons/lesson_4.md
        - Lesson 5: Intermediate/Lessons/lesson_5.md
        - Lesson 6: Intermediate/Lessons/lesson_6.md
        - Lesson 7: Intermediate/Lessons/lesson_7.md
        - Lesson 8: Intermediate/Lessons/lesson_8.md
        - Lesson 9: Intermediate/Lessons/lesson_9.md
        - Lesson 10: Intermediate/Lessons/lesson_10.md
        - Lesson 11: Intermediate/Lessons/lesson_11.md
        - Lesson 12: Intermediate/Lessons/lesson_12.md
        - Lesson 13: Intermediate/Lessons/lesson_13.md
        - Lesson 14: Intermediate/Lessons/lesson_14.md
        - Lesson 15: Intermediate/Lessons/lesson_15.md
        - Lesson 16: Intermediate/Lessons/lesson_16.md
        - Lesson 17: Intermediate/Lessons/lesson_17.md
        - Lesson 18: Intermediate/Lessons/lesson_18.md
        - Lesson 19: Intermediate/Lessons/lesson_19.md
        - Lesson 20: Intermediate/Lessons/lesson_20.md
        - Lesson 21: Intermediate/Lessons/lesson_21.md
        - Lesson 22: Intermediate/Lessons/lesson_22.md
        - Lesson 23: Intermediate/Lessons/lesson_23.md
        - Lesson 24: Intermediate/Lessons/lesson_24.md
        - Lesson 25: Intermediate/Lessons/lesson_25.md
        - Lesson 26: Intermediate/Lessons/lesson_26.md
        - Lesson 27: Intermediate/Lessons/lesson_27.md
        - Lesson 28: Intermediate/Lessons/lesson_28.md
        - Lesson 29: Intermediate/Lessons/lesson_29.md
        - Lesson 30: Intermediate/Lessons/lesson_30.md
        - Lesson 31: Intermediate/Lessons/lesson_31.md
        - Lesson 32: Intermediate/Lessons/lesson_32.md
        - Lesson 33: Intermediate/Lessons/lesson_33.md
        - Lesson 34: Intermediate/Lessons/lesson_34.md
        - Lesson 35: Intermediate/Lessons/lesson_35.md
        - Lesson 36: Intermediate/Lessons/lesson_36.md
        - Lesson 37: Intermediate/Lessons/lesson_37.md
        - Lesson 38: Intermediate/Lessons/lesson_38.md
        - Lesson 39: Intermediate/Lessons/lesson_39.md
        - Lesson 40: Intermediate/Lessons/lesson_40.md
        - Lesson 41: Intermediate/Lessons/lesson_41.md
        - Lesson 42: Intermediate/Lessons/lesson_42.md
        - Lesson 43: Intermediate/Lessons/lesson_43.md
        - Lesson 44: Intermediate/Lessons/lesson_44.md
        - Lesson 45: Intermediate/Lessons/lesson_45.md
        - Lesson 46: Intermediate/Lessons/lesson_46.md
        - Lesson 47: Intermediate/Lessons/lesson_47.md
        - Lesson 48: Intermediate/Lessons/lesson_48.md
        - Lesson 49: Intermediate/Lessons/lesson_49.md
        - Lesson 50: Intermediate/Lessons/lesson_50.md
        - Lesson 51: Intermediate/Lessons/lesson_51.md
        - Lesson 52: Intermediate/Lessons/lesson_52.md
        - Lesson 53: Intermediate/Lessons/lesson_53.md
        - Lesson 54: Intermediate/Lessons/lesson_54.md
        - Lesson 55: Intermediate/Lessons/lesson_55.md
        - Lesson 56: Intermediate/Lessons/lesson_56.md
        - Lesson 57: Intermediate/Lessons/lesson_57.md
        - Lesson 58: Intermediate/Lessons/lesson_58.md
        - Lesson 59: Intermediate/Lessons/lesson_59.md
        - Lesson 60: Intermediate/Lessons/lesson_60.md
        - Lesson 61: Intermediate/Lessons/lesson_61.md
        - Lesson 62: Intermediate/Lessons/lesson_62.md
        - Lesson 63: Intermediate/Lessons/lesson_63.md
        - Lesson 64: Intermediate/Lessons/lesson_64.md
        - Lesson 65: Intermediate/Lessons/lesson_65.md
        - Lesson 66: Intermediate/Lessons/lesson_66.md
        - Lesson 67: Intermediate/Lessons/lesson_67.md
        - Lesson 68: Intermediate/Lessons/lesson_68.md
        - Lesson 69: Intermediate/Lessons/lesson_69.md
        - Lesson 70: Intermediate/Lessons/lesson_70.md
        - Lesson 71: Intermediate/Lessons/lesson_71.md
        - Lesson 72: Intermediate/Lessons/lesson_72.md
        - Lesson 73: Intermediate/Lessons/lesson_73.md
        - Lesson 74: Intermediate/Lessons/lesson_74.md
        - Lesson 75: Intermediate/Lessons/lesson_75.md
        - Lesson 76: Intermediate/Lessons/lesson_76.md
        - Lesson 77: Intermediate/Lessons/lesson_77.md
        - Lesson 78: Intermediate/Lessons/lesson_78.md
        - Lesson 79: Intermediate/Lessons/lesson_79.md
        - Lesson 80: Intermediate/Lessons/lesson_80.md
        - Lesson 81: Intermediate/Lessons/lesson_81.md
        - Lesson 82: Intermediate/Lessons/lesson_82.md
        - Lesson 83: Intermediate/Lessons/lesson_83.md
        - Lesson 84: Intermediate/Lessons/lesson_84.md
        - Lesson 85: Intermediate/Lessons/lesson_85.md
        - Lesson 86: Intermediate/Lessons/lesson_86.md
        - Lesson 87: Intermediate/Lessons/lesson_87.md
        - Lesson 88: Intermediate/Lessons/lesson_88.md
        - Lesson 89: Intermediate/Lessons/lesson_89.md
        - Lesson 90: Intermediate/Lessons/lesson_90.md
        - Lesson 91: Intermediate/Lessons/lesson_91.md
        - Lesson 92: Intermediate/Lessons/lesson_92.md
        - Lesson 93: Intermediate/Lessons/lesson_93.md
        - Lesson 94: Intermediate/Lessons/lesson_94.md
        - Lesson 95: Intermediate/Lessons/lesson_95.md
        - Lesson 96: Intermediate/Lessons/lesson_96.md
        - Lesson 97: Intermediate/Lessons/lesson_97.md
        - Lesson 98: Intermediate/Lessons/lesson_98.md
        - Lesson 99: Intermediate/Lessons/lesson_99.md
        - Lesson 100: Intermediate/Lessons/lesson_100.md
          
        
  - Advanced:
      - Overview: Advanced/index.md
      - Learn by Subject:
        - Decision Making: Advanced/learn-by-subject/decision-making.md
        - Machine Learning: Advanced/learn-by-subject/machine-learning.md
        - Probability & Statistics: Advanced/learn-by-subject/probability-and-statistics.md
      - Lessons:
        - Lesson 1: Advanced/Lessons/lesson_1.md
        - Lesson 2: Advanced/Lessons/lesson_2.md
        - Lesson 3: Advanced/Lessons/lesson_3.md
       
  - Tech-to-market:
      - Overview: Tech-to-market/index.md
      - Learn by Subject: 
        - Business Fundamentals: Tech-to-market/learn-by-subject/business-fundamentals.md
        - Innovation and Entrepreneurship: Tech-to-market/learn-by-subject/innovation-and-entrepreneurship.md
        - Marketing and Sales: Tech-to-market/learn-by-subject/marketing-and-sales.md
        - Product Management: Tech-to-market/learn-by-subject/product-management.md
           
  - Company:
      - About us: about-us.md
      - Contributing: contributing.md
      - FAQ: faq.md
  


markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
