site_name: "Botshare Book"
site_url: "https://merilynn-64.github.io/Botshare_document/"
repo_url: "https://github.com/openAMRobot"
repo_name: "GitHub"

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.section
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: dark blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: assets/logo.jpg
  favicon: assets/favicon.png 

extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:info@botshare.ai
    - icon: fontawesome/brands/github
      link: https://github.com/openAMRobot
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/botshare
    - icon: fontawesome/brands/github
      link: https://github.com/openAMRobot
    - icon: fontawesome/solid/heart
      link: https://your-donation-link.com
    - icon: fontawesome/solid/info-circle
      link: https://botshare.ai

nav:
  - Homepage: index.md
  - L1 - Incubation:
      - Overview: L1/index.md
      - Lesson 1: L1/lesson-1.md
      - Lesson 2: L1/lesson-2.md
  - L2 - Acceleration:
      - Overview: L2/index.md
      - Lesson 1: L2/lesson-1.md
      - Lesson 2: L2/lesson-2.md
  - L3 - Mastery:
      - Overview: L3/index.md
      - Lesson 1: L3/lesson-1.md
      - Lesson 2: L3/lesson-3.md
  - About Us: about/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
