site_name: "Botshare Book"
site_url: "https://merilynn-64.github.io/Botshare_document/"
repo_url: "https://github.com/openAMRobot"
repo_name: "GitHub"

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.path
    - navgation.indexes
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: dark blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: assets/logo.jpg
  favicon: assets/favicon.png 

extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:info@botshare.ai
    - icon: fontawesome/brands/github
      link: https://github.com/openAMRobot
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/botshare
    - icon: fontawesome/brands/github
      link: https://github.com/openAMRobot
    - icon: fontawesome/solid/heart
      link: https://your-donation-link.com
nav:
  - Homepage: index.md

  - L1 Incubation:
      - Homepage: L1-Incubation/home.md
      - Overview: L1-Incubation/index.md
      - Lessons:
          - Lesson 1: L1-Incubation/Lessons/lesson-1.md
          - Lesson 2: L1-Incubation/Lessons/lesson-2.md
          - Lesson 3: L1-Incubation/Lessons/lesson-3.md
      - About Us: about-us.md

  - L2 Acceleration:
      - Homepage: L2-Acceleration/home.md
      - Overview: L2-Acceleration/index.md
      - Lessons:
          - Lesson 1: L2-Acceleration/Lessons/lesson-1.md
          - Lesson 2: L2-Acceleration/Lessons/lesson-2.md
      - About Us: about-us.md

  - L3 Mastery:
      - Homepage: L3-Mastery/home.md
      - Overview: L3-Mastery/index.md
      - Lessons:
          - Lesson 1: L3-Mastery/Lessons/lesson-1.md
          - Lesson 2: L3-Mastery/Lessons/lesson-2.md
      - About Us: about-us.md
    




markdown_extensions:
  - admonition
  - pymdownx.details
