site_name: "Botshare Book"
site_url: "https://merilynn-64.github.io/Botshare_document/"
repo_url: "https://github.com/openAMRobot"
repo_name: "GitHub"

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: dark blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: assets/logo.jpg
  favicon: assets/favicon.png 

extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:info@botshare.ai
    - icon: fontawesome/brands/github
      link: https://github.com/openAMRobot
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/botshare

nav:
  - Home:
      - Welcome: overview.md

      - Overview: 
          - Our Solution: our-solution.md
          - What You Will Learn: what-you-will-learn.md
          - Course Outcomes: course-outcomes.md

      - Course Framework:
          - L1 - Incubation: l1-incubation.md
          - L2 - Acceleration: l2-acceleration.md
          - Core Pillars: core-pillars.md

      - Learning Model:
          - AI-Powered Adaptive Learning: ai-powered-adaptive-learning.md
          - Industry-Aligned Learning Model: industry-aligned-learning-model.md
          - Professional Open-Source Learning: professional-open-source-learning.md
          
      - Audience & Support:
          - Who Benefits: who-benefits.md
          - Target Audience & Career Paths: target-audience-career-paths.md
          - Certification & Career Support: certification-career-support.md
          - Get started: get-started-now.md

    
  - Start Now:
      - Introduction: getting_started.md
      - Use Cases: use-cases.md
  - Botshare Framework:
      - L1 - Incubation: level-1-incubation.md
      - L2 - Acceleration: level-2-acceleration.md
      - References: references.md
  - Company:
      - Company Overview: company-overview.md
      - Contributing: contributing.md
      - FAQ: faq.md
  - GitHub Repo: https://github.com/openAMRobot

markdown_extensions:
  - admonition
  - pymdownx.details
